# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
