# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20181020_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperiod',
            name='booking_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingperiod',
            name='booking_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='priceperiod',
            name='price_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='priceperiod',
            name='price_start_date',
            field=models.DateField(),
        ),
    ]
